name: Prueba

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
    branches: [master]
jobs:
  test_changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Add any build steps here. For example:
      # - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 30d
          projectId: your-Firebase-project-ID
      - name: Install dependencies
        run: npm ci

      - name: Build and run development server
        run: npm start&

      - name: Run tests
        run: npm run sample-test
